version: '2'
services:
  web:
    volumes:
      - ./:/app/
    image: webdevops/php-apache
    container_name: algoritmos-web
    ports:
      - "80:80"
    restart: always
    environment:
      WEB_DOCUMENT_ROOT: /app
